#!/usr/bin/env python3
# -*- coding: utf-8 -*-

import tkinter as tk
from time import localtime, strftime

class heure(tk.Tk):
	def __init__(self):
		tk.Tk.__init__(self)
		self.get_time = strftime("%H:%M:%S", localtime())
		self.time = tk.Label(self, text=self.get_time)
		self.time.pack()
		
		self.boutton_quit = tk.Button(self, text="quit", fg="blue", command=self.quit)
		self.boutton_quit.pack()

		self.gettime()

	def gettime(self):
		get_time = strftime("%H:%M:%S", localtime())
		self.time.configure(text=get_time)
		self.after(1000, self.gettime)

def main():
	app = heure()
	app.title("heure")
	app.mainloop()

if __name__ == "__main__":
	main()
