#!/usr/bin/env python3
# -*- coding: utf-8 -*-

import tkinter as tk
from time import localtime, strftime

class heure(tk.Tk):
	def __init__(self):
		tk.Tk.__init__(self)
		self.time = tk.Label(self, text=self.gettime())
		self.time.pack()
		self.boutton_quit = tk.Button(self, text="quit", fg="blue", command=self.quit)
		self.boutton_quit.pack()

	def gettime(self):
		time = strftime("%H:%M:%S", localtime())
		return time

def main():
	app = heure()
	app.title("heure")
	app.mainloop()

if __name__ == "__main__":
	main()
